/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/tiiuae/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/msg/control_interface_diagnostics.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/ControlInterfaceDiagnostics", ControlInterfaceDiagnosticsTypeSupport)
}

// Do not create instances of this type directly. Always use NewControlInterfaceDiagnostics
// function instead.
type ControlInterfaceDiagnostics struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Armed bool `yaml:"armed"`
	Airborne bool `yaml:"airborne"`
	Moving bool `yaml:"moving"`
	MissionFinished bool `yaml:"mission_finished"`
	LastMissionSize uint8 `yaml:"last_mission_size"`
	GpsOriginSet bool `yaml:"gps_origin_set"`
	GettingOdom bool `yaml:"getting_odom"`
	GettingControlMode bool `yaml:"getting_control_mode"`
	GettingLandSensor bool `yaml:"getting_land_sensor"`
	ManualControl bool `yaml:"manual_control"`
}

// NewControlInterfaceDiagnostics creates a new ControlInterfaceDiagnostics with default values.
func NewControlInterfaceDiagnostics() *ControlInterfaceDiagnostics {
	self := ControlInterfaceDiagnostics{}
	self.SetDefaults()
	return &self
}

func (t *ControlInterfaceDiagnostics) Clone() *ControlInterfaceDiagnostics {
	c := &ControlInterfaceDiagnostics{}
	c.Header = *t.Header.Clone()
	c.Armed = t.Armed
	c.Airborne = t.Airborne
	c.Moving = t.Moving
	c.MissionFinished = t.MissionFinished
	c.LastMissionSize = t.LastMissionSize
	c.GpsOriginSet = t.GpsOriginSet
	c.GettingOdom = t.GettingOdom
	c.GettingControlMode = t.GettingControlMode
	c.GettingLandSensor = t.GettingLandSensor
	c.ManualControl = t.ManualControl
	return c
}

func (t *ControlInterfaceDiagnostics) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ControlInterfaceDiagnostics) SetDefaults() {
	t.Header.SetDefaults()
	t.Armed = false
	t.Airborne = false
	t.Moving = false
	t.MissionFinished = false
	t.LastMissionSize = 0
	t.GpsOriginSet = false
	t.GettingOdom = false
	t.GettingControlMode = false
	t.GettingLandSensor = false
	t.ManualControl = false
}

// CloneControlInterfaceDiagnosticsSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneControlInterfaceDiagnosticsSlice(dst, src []ControlInterfaceDiagnostics) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ControlInterfaceDiagnosticsTypeSupport types.MessageTypeSupport = _ControlInterfaceDiagnosticsTypeSupport{}

type _ControlInterfaceDiagnosticsTypeSupport struct{}

func (t _ControlInterfaceDiagnosticsTypeSupport) New() types.Message {
	return NewControlInterfaceDiagnostics()
}

func (t _ControlInterfaceDiagnosticsTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__msg__ControlInterfaceDiagnostics
	return (unsafe.Pointer)(C.fog_msgs__msg__ControlInterfaceDiagnostics__create())
}

func (t _ControlInterfaceDiagnosticsTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__msg__ControlInterfaceDiagnostics__destroy((*C.fog_msgs__msg__ControlInterfaceDiagnostics)(pointer_to_free))
}

func (t _ControlInterfaceDiagnosticsTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ControlInterfaceDiagnostics)
	mem := (*C.fog_msgs__msg__ControlInterfaceDiagnostics)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	mem.armed = C.bool(m.Armed)
	mem.airborne = C.bool(m.Airborne)
	mem.moving = C.bool(m.Moving)
	mem.mission_finished = C.bool(m.MissionFinished)
	mem.last_mission_size = C.uint8_t(m.LastMissionSize)
	mem.gps_origin_set = C.bool(m.GpsOriginSet)
	mem.getting_odom = C.bool(m.GettingOdom)
	mem.getting_control_mode = C.bool(m.GettingControlMode)
	mem.getting_land_sensor = C.bool(m.GettingLandSensor)
	mem.manual_control = C.bool(m.ManualControl)
}

func (t _ControlInterfaceDiagnosticsTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ControlInterfaceDiagnostics)
	mem := (*C.fog_msgs__msg__ControlInterfaceDiagnostics)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	m.Armed = bool(mem.armed)
	m.Airborne = bool(mem.airborne)
	m.Moving = bool(mem.moving)
	m.MissionFinished = bool(mem.mission_finished)
	m.LastMissionSize = uint8(mem.last_mission_size)
	m.GpsOriginSet = bool(mem.gps_origin_set)
	m.GettingOdom = bool(mem.getting_odom)
	m.GettingControlMode = bool(mem.getting_control_mode)
	m.GettingLandSensor = bool(mem.getting_land_sensor)
	m.ManualControl = bool(mem.manual_control)
}

func (t _ControlInterfaceDiagnosticsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__msg__ControlInterfaceDiagnostics())
}

type CControlInterfaceDiagnostics = C.fog_msgs__msg__ControlInterfaceDiagnostics
type CControlInterfaceDiagnostics__Sequence = C.fog_msgs__msg__ControlInterfaceDiagnostics__Sequence

func ControlInterfaceDiagnostics__Sequence_to_Go(goSlice *[]ControlInterfaceDiagnostics, cSlice CControlInterfaceDiagnostics__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ControlInterfaceDiagnostics, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__msg__ControlInterfaceDiagnostics__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__msg__ControlInterfaceDiagnostics * uintptr(i)),
		))
		ControlInterfaceDiagnosticsTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ControlInterfaceDiagnostics__Sequence_to_C(cSlice *CControlInterfaceDiagnostics__Sequence, goSlice []ControlInterfaceDiagnostics) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__msg__ControlInterfaceDiagnostics)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__msg__ControlInterfaceDiagnostics * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__msg__ControlInterfaceDiagnostics)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__msg__ControlInterfaceDiagnostics * uintptr(i)),
		))
		ControlInterfaceDiagnosticsTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ControlInterfaceDiagnostics__Array_to_Go(goSlice []ControlInterfaceDiagnostics, cSlice []CControlInterfaceDiagnostics) {
	for i := 0; i < len(cSlice); i++ {
		ControlInterfaceDiagnosticsTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ControlInterfaceDiagnostics__Array_to_C(cSlice []CControlInterfaceDiagnostics, goSlice []ControlInterfaceDiagnostics) {
	for i := 0; i < len(goSlice); i++ {
		ControlInterfaceDiagnosticsTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
