/*
Package msgs imports this bundle of all known messages for programs that need to
dynamically parse incoming messages. Such as the 'rclgo' command line client.

The contents of msgs are always autogenerated from the 'rclgo-gen generate'
-command
*/
package msgs
