/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package msgs

import (
	_ "github.com/mehmetkillioglu/rclgo-msgs/action_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/action_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/actionlib_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/builtin_interfaces/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/composition_interfaces/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/diagnostic_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/diagnostic_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/example_interfaces/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/example_interfaces/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/fog_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/geometry_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/lifecycle_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/lifecycle_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/logging_demo/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/map_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/map_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/nav_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/nav_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/pcl_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/pcl_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/pendulum_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/px4_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/rcl_interfaces/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/rcl_interfaces/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/rmw_dds_common/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/rosgraph_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/sensor_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/sensor_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/shape_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/statistics_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/std_srvs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/stereo_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/test_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/test_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/tf2_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/tf2_msgs/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/trajectory_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/turtlesim/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/turtlesim/srv" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/unique_identifier_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/visualization_msgs/msg" //
	_ "github.com/mehmetkillioglu/rclgo-msgs/visualization_msgs/srv" //
)
