/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/camera_status.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("px4_msgs/CameraStatus", CameraStatusTypeSupport)
}

// Do not create instances of this type directly. Always use NewCameraStatus
// function instead.
type CameraStatus struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	ActiveSysId uint8 `yaml:"active_sys_id"`// mavlink system id of the currently active camera
	ActiveCompId uint8 `yaml:"active_comp_id"`// mavlink component id of currently active camera
}

// NewCameraStatus creates a new CameraStatus with default values.
func NewCameraStatus() *CameraStatus {
	self := CameraStatus{}
	self.SetDefaults()
	return &self
}

func (t *CameraStatus) Clone() *CameraStatus {
	c := &CameraStatus{}
	c.Timestamp = t.Timestamp
	c.ActiveSysId = t.ActiveSysId
	c.ActiveCompId = t.ActiveCompId
	return c
}

func (t *CameraStatus) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CameraStatus) SetDefaults() {
	t.Timestamp = 0
	t.ActiveSysId = 0
	t.ActiveCompId = 0
}

// CloneCameraStatusSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCameraStatusSlice(dst, src []CameraStatus) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CameraStatusTypeSupport types.MessageTypeSupport = _CameraStatusTypeSupport{}

type _CameraStatusTypeSupport struct{}

func (t _CameraStatusTypeSupport) New() types.Message {
	return NewCameraStatus()
}

func (t _CameraStatusTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__CameraStatus
	return (unsafe.Pointer)(C.px4_msgs__msg__CameraStatus__create())
}

func (t _CameraStatusTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__CameraStatus__destroy((*C.px4_msgs__msg__CameraStatus)(pointer_to_free))
}

func (t _CameraStatusTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CameraStatus)
	mem := (*C.px4_msgs__msg__CameraStatus)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	mem.active_sys_id = C.uint8_t(m.ActiveSysId)
	mem.active_comp_id = C.uint8_t(m.ActiveCompId)
}

func (t _CameraStatusTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CameraStatus)
	mem := (*C.px4_msgs__msg__CameraStatus)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	m.ActiveSysId = uint8(mem.active_sys_id)
	m.ActiveCompId = uint8(mem.active_comp_id)
}

func (t _CameraStatusTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__CameraStatus())
}

type CCameraStatus = C.px4_msgs__msg__CameraStatus
type CCameraStatus__Sequence = C.px4_msgs__msg__CameraStatus__Sequence

func CameraStatus__Sequence_to_Go(goSlice *[]CameraStatus, cSlice CCameraStatus__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CameraStatus, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__CameraStatus__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__CameraStatus * uintptr(i)),
		))
		CameraStatusTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func CameraStatus__Sequence_to_C(cSlice *CCameraStatus__Sequence, goSlice []CameraStatus) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__CameraStatus)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__CameraStatus * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__CameraStatus)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__CameraStatus * uintptr(i)),
		))
		CameraStatusTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func CameraStatus__Array_to_Go(goSlice []CameraStatus, cSlice []CCameraStatus) {
	for i := 0; i < len(cSlice); i++ {
		CameraStatusTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CameraStatus__Array_to_C(cSlice []CCameraStatus, goSlice []CameraStatus) {
	for i := 0; i < len(goSlice); i++ {
		CameraStatusTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
