/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/sensor_baro.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("px4_msgs/SensorBaro", SensorBaroTypeSupport)
}

// Do not create instances of this type directly. Always use NewSensorBaro
// function instead.
type SensorBaro struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	TimestampSample uint64 `yaml:"timestamp_sample"`
	DeviceId uint32 `yaml:"device_id"`// unique device ID for the sensor that does not change between power cycles
	ErrorCount uint32 `yaml:"error_count"`
	Pressure float32 `yaml:"pressure"`// static pressure measurement in millibar
	Temperature float32 `yaml:"temperature"`// static temperature measurement in deg Celsius
}

// NewSensorBaro creates a new SensorBaro with default values.
func NewSensorBaro() *SensorBaro {
	self := SensorBaro{}
	self.SetDefaults()
	return &self
}

func (t *SensorBaro) Clone() *SensorBaro {
	c := &SensorBaro{}
	c.Timestamp = t.Timestamp
	c.TimestampSample = t.TimestampSample
	c.DeviceId = t.DeviceId
	c.ErrorCount = t.ErrorCount
	c.Pressure = t.Pressure
	c.Temperature = t.Temperature
	return c
}

func (t *SensorBaro) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SensorBaro) SetDefaults() {
	t.Timestamp = 0
	t.TimestampSample = 0
	t.DeviceId = 0
	t.ErrorCount = 0
	t.Pressure = 0
	t.Temperature = 0
}

// CloneSensorBaroSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSensorBaroSlice(dst, src []SensorBaro) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SensorBaroTypeSupport types.MessageTypeSupport = _SensorBaroTypeSupport{}

type _SensorBaroTypeSupport struct{}

func (t _SensorBaroTypeSupport) New() types.Message {
	return NewSensorBaro()
}

func (t _SensorBaroTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__SensorBaro
	return (unsafe.Pointer)(C.px4_msgs__msg__SensorBaro__create())
}

func (t _SensorBaroTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__SensorBaro__destroy((*C.px4_msgs__msg__SensorBaro)(pointer_to_free))
}

func (t _SensorBaroTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SensorBaro)
	mem := (*C.px4_msgs__msg__SensorBaro)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	mem.timestamp_sample = C.uint64_t(m.TimestampSample)
	mem.device_id = C.uint32_t(m.DeviceId)
	mem.error_count = C.uint32_t(m.ErrorCount)
	mem.pressure = C.float(m.Pressure)
	mem.temperature = C.float(m.Temperature)
}

func (t _SensorBaroTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SensorBaro)
	mem := (*C.px4_msgs__msg__SensorBaro)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	m.TimestampSample = uint64(mem.timestamp_sample)
	m.DeviceId = uint32(mem.device_id)
	m.ErrorCount = uint32(mem.error_count)
	m.Pressure = float32(mem.pressure)
	m.Temperature = float32(mem.temperature)
}

func (t _SensorBaroTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__SensorBaro())
}

type CSensorBaro = C.px4_msgs__msg__SensorBaro
type CSensorBaro__Sequence = C.px4_msgs__msg__SensorBaro__Sequence

func SensorBaro__Sequence_to_Go(goSlice *[]SensorBaro, cSlice CSensorBaro__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SensorBaro, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__SensorBaro__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__SensorBaro * uintptr(i)),
		))
		SensorBaroTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SensorBaro__Sequence_to_C(cSlice *CSensorBaro__Sequence, goSlice []SensorBaro) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__SensorBaro)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__SensorBaro * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__SensorBaro)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__SensorBaro * uintptr(i)),
		))
		SensorBaroTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SensorBaro__Array_to_Go(goSlice []SensorBaro, cSlice []CSensorBaro) {
	for i := 0; i < len(cSlice); i++ {
		SensorBaroTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SensorBaro__Array_to_C(cSlice []CSensorBaro, goSlice []SensorBaro) {
	for i := 0; i < len(goSlice); i++ {
		SensorBaroTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
