/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	fog_msgs_msg "github.com/tiiuae/rclgo-msgs/fog_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/change_odometry.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/ChangeOdometry_Request", ChangeOdometry_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewChangeOdometry_Request
// function instead.
type ChangeOdometry_Request struct {
	OdometryType fog_msgs_msg.OdometryType `yaml:"odometry_type"`
}

// NewChangeOdometry_Request creates a new ChangeOdometry_Request with default values.
func NewChangeOdometry_Request() *ChangeOdometry_Request {
	self := ChangeOdometry_Request{}
	self.SetDefaults()
	return &self
}

func (t *ChangeOdometry_Request) Clone() *ChangeOdometry_Request {
	c := &ChangeOdometry_Request{}
	c.OdometryType = *t.OdometryType.Clone()
	return c
}

func (t *ChangeOdometry_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ChangeOdometry_Request) SetDefaults() {
	t.OdometryType.SetDefaults()
}

// CloneChangeOdometry_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneChangeOdometry_RequestSlice(dst, src []ChangeOdometry_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ChangeOdometry_RequestTypeSupport types.MessageTypeSupport = _ChangeOdometry_RequestTypeSupport{}

type _ChangeOdometry_RequestTypeSupport struct{}

func (t _ChangeOdometry_RequestTypeSupport) New() types.Message {
	return NewChangeOdometry_Request()
}

func (t _ChangeOdometry_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__ChangeOdometry_Request
	return (unsafe.Pointer)(C.fog_msgs__srv__ChangeOdometry_Request__create())
}

func (t _ChangeOdometry_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__ChangeOdometry_Request__destroy((*C.fog_msgs__srv__ChangeOdometry_Request)(pointer_to_free))
}

func (t _ChangeOdometry_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ChangeOdometry_Request)
	mem := (*C.fog_msgs__srv__ChangeOdometry_Request)(dst)
	fog_msgs_msg.OdometryTypeTypeSupport.AsCStruct(unsafe.Pointer(&mem.odometry_type), &m.OdometryType)
}

func (t _ChangeOdometry_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ChangeOdometry_Request)
	mem := (*C.fog_msgs__srv__ChangeOdometry_Request)(ros2_message_buffer)
	fog_msgs_msg.OdometryTypeTypeSupport.AsGoStruct(&m.OdometryType, unsafe.Pointer(&mem.odometry_type))
}

func (t _ChangeOdometry_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__ChangeOdometry_Request())
}

type CChangeOdometry_Request = C.fog_msgs__srv__ChangeOdometry_Request
type CChangeOdometry_Request__Sequence = C.fog_msgs__srv__ChangeOdometry_Request__Sequence

func ChangeOdometry_Request__Sequence_to_Go(goSlice *[]ChangeOdometry_Request, cSlice CChangeOdometry_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ChangeOdometry_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__ChangeOdometry_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Request * uintptr(i)),
		))
		ChangeOdometry_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ChangeOdometry_Request__Sequence_to_C(cSlice *CChangeOdometry_Request__Sequence, goSlice []ChangeOdometry_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__ChangeOdometry_Request)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__ChangeOdometry_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Request * uintptr(i)),
		))
		ChangeOdometry_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ChangeOdometry_Request__Array_to_Go(goSlice []ChangeOdometry_Request, cSlice []CChangeOdometry_Request) {
	for i := 0; i < len(cSlice); i++ {
		ChangeOdometry_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ChangeOdometry_Request__Array_to_C(cSlice []CChangeOdometry_Request, goSlice []ChangeOdometry_Request) {
	for i := 0; i < len(goSlice); i++ {
		ChangeOdometry_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
