/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	fog_msgs_msg "github.com/tiiuae/rclgo-msgs/fog_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/change_odometry.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/ChangeOdometry_Response", ChangeOdometry_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewChangeOdometry_Response
// function instead.
type ChangeOdometry_Response struct {
	Success bool `yaml:"success"`
	Message string `yaml:"message"`
	OdometryType fog_msgs_msg.OdometryType `yaml:"odometry_type"`
}

// NewChangeOdometry_Response creates a new ChangeOdometry_Response with default values.
func NewChangeOdometry_Response() *ChangeOdometry_Response {
	self := ChangeOdometry_Response{}
	self.SetDefaults()
	return &self
}

func (t *ChangeOdometry_Response) Clone() *ChangeOdometry_Response {
	c := &ChangeOdometry_Response{}
	c.Success = t.Success
	c.Message = t.Message
	c.OdometryType = *t.OdometryType.Clone()
	return c
}

func (t *ChangeOdometry_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ChangeOdometry_Response) SetDefaults() {
	t.Success = false
	t.Message = ""
	t.OdometryType.SetDefaults()
}

// CloneChangeOdometry_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneChangeOdometry_ResponseSlice(dst, src []ChangeOdometry_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ChangeOdometry_ResponseTypeSupport types.MessageTypeSupport = _ChangeOdometry_ResponseTypeSupport{}

type _ChangeOdometry_ResponseTypeSupport struct{}

func (t _ChangeOdometry_ResponseTypeSupport) New() types.Message {
	return NewChangeOdometry_Response()
}

func (t _ChangeOdometry_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__ChangeOdometry_Response
	return (unsafe.Pointer)(C.fog_msgs__srv__ChangeOdometry_Response__create())
}

func (t _ChangeOdometry_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__ChangeOdometry_Response__destroy((*C.fog_msgs__srv__ChangeOdometry_Response)(pointer_to_free))
}

func (t _ChangeOdometry_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ChangeOdometry_Response)
	mem := (*C.fog_msgs__srv__ChangeOdometry_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.message), m.Message)
	fog_msgs_msg.OdometryTypeTypeSupport.AsCStruct(unsafe.Pointer(&mem.odometry_type), &m.OdometryType)
}

func (t _ChangeOdometry_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ChangeOdometry_Response)
	mem := (*C.fog_msgs__srv__ChangeOdometry_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Message, unsafe.Pointer(&mem.message))
	fog_msgs_msg.OdometryTypeTypeSupport.AsGoStruct(&m.OdometryType, unsafe.Pointer(&mem.odometry_type))
}

func (t _ChangeOdometry_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__ChangeOdometry_Response())
}

type CChangeOdometry_Response = C.fog_msgs__srv__ChangeOdometry_Response
type CChangeOdometry_Response__Sequence = C.fog_msgs__srv__ChangeOdometry_Response__Sequence

func ChangeOdometry_Response__Sequence_to_Go(goSlice *[]ChangeOdometry_Response, cSlice CChangeOdometry_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ChangeOdometry_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__ChangeOdometry_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Response * uintptr(i)),
		))
		ChangeOdometry_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ChangeOdometry_Response__Sequence_to_C(cSlice *CChangeOdometry_Response__Sequence, goSlice []ChangeOdometry_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__ChangeOdometry_Response)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__ChangeOdometry_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__ChangeOdometry_Response * uintptr(i)),
		))
		ChangeOdometry_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ChangeOdometry_Response__Array_to_Go(goSlice []ChangeOdometry_Response, cSlice []CChangeOdometry_Response) {
	for i := 0; i < len(cSlice); i++ {
		ChangeOdometry_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ChangeOdometry_Response__Array_to_C(cSlice []CChangeOdometry_Response, goSlice []ChangeOdometry_Response) {
	for i := 0; i < len(goSlice); i++ {
		ChangeOdometry_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
