/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/get_bool.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/GetBool_Request", GetBool_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetBool_Request
// function instead.
type GetBool_Request struct {
}

// NewGetBool_Request creates a new GetBool_Request with default values.
func NewGetBool_Request() *GetBool_Request {
	self := GetBool_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetBool_Request) Clone() *GetBool_Request {
	c := &GetBool_Request{}
	return c
}

func (t *GetBool_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetBool_Request) SetDefaults() {
}

// CloneGetBool_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetBool_RequestSlice(dst, src []GetBool_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetBool_RequestTypeSupport types.MessageTypeSupport = _GetBool_RequestTypeSupport{}

type _GetBool_RequestTypeSupport struct{}

func (t _GetBool_RequestTypeSupport) New() types.Message {
	return NewGetBool_Request()
}

func (t _GetBool_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__GetBool_Request
	return (unsafe.Pointer)(C.fog_msgs__srv__GetBool_Request__create())
}

func (t _GetBool_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__GetBool_Request__destroy((*C.fog_msgs__srv__GetBool_Request)(pointer_to_free))
}

func (t _GetBool_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetBool_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetBool_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__GetBool_Request())
}

type CGetBool_Request = C.fog_msgs__srv__GetBool_Request
type CGetBool_Request__Sequence = C.fog_msgs__srv__GetBool_Request__Sequence

func GetBool_Request__Sequence_to_Go(goSlice *[]GetBool_Request, cSlice CGetBool_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetBool_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__GetBool_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetBool_Request * uintptr(i)),
		))
		GetBool_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetBool_Request__Sequence_to_C(cSlice *CGetBool_Request__Sequence, goSlice []GetBool_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__GetBool_Request)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__GetBool_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__GetBool_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetBool_Request * uintptr(i)),
		))
		GetBool_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetBool_Request__Array_to_Go(goSlice []GetBool_Request, cSlice []CGetBool_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetBool_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetBool_Request__Array_to_C(cSlice []CGetBool_Request, goSlice []GetBool_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetBool_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
