/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/get_origin.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/GetOrigin_Response", GetOrigin_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetOrigin_Response
// function instead.
type GetOrigin_Response struct {
	Latitude float64 `yaml:"latitude"`
	Longitude float64 `yaml:"longitude"`
	Success bool `yaml:"success"`
}

// NewGetOrigin_Response creates a new GetOrigin_Response with default values.
func NewGetOrigin_Response() *GetOrigin_Response {
	self := GetOrigin_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetOrigin_Response) Clone() *GetOrigin_Response {
	c := &GetOrigin_Response{}
	c.Latitude = t.Latitude
	c.Longitude = t.Longitude
	c.Success = t.Success
	return c
}

func (t *GetOrigin_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetOrigin_Response) SetDefaults() {
	t.Latitude = 0
	t.Longitude = 0
	t.Success = false
}

// CloneGetOrigin_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetOrigin_ResponseSlice(dst, src []GetOrigin_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetOrigin_ResponseTypeSupport types.MessageTypeSupport = _GetOrigin_ResponseTypeSupport{}

type _GetOrigin_ResponseTypeSupport struct{}

func (t _GetOrigin_ResponseTypeSupport) New() types.Message {
	return NewGetOrigin_Response()
}

func (t _GetOrigin_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__GetOrigin_Response
	return (unsafe.Pointer)(C.fog_msgs__srv__GetOrigin_Response__create())
}

func (t _GetOrigin_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__GetOrigin_Response__destroy((*C.fog_msgs__srv__GetOrigin_Response)(pointer_to_free))
}

func (t _GetOrigin_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetOrigin_Response)
	mem := (*C.fog_msgs__srv__GetOrigin_Response)(dst)
	mem.latitude = C.double(m.Latitude)
	mem.longitude = C.double(m.Longitude)
	mem.success = C.bool(m.Success)
}

func (t _GetOrigin_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetOrigin_Response)
	mem := (*C.fog_msgs__srv__GetOrigin_Response)(ros2_message_buffer)
	m.Latitude = float64(mem.latitude)
	m.Longitude = float64(mem.longitude)
	m.Success = bool(mem.success)
}

func (t _GetOrigin_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__GetOrigin_Response())
}

type CGetOrigin_Response = C.fog_msgs__srv__GetOrigin_Response
type CGetOrigin_Response__Sequence = C.fog_msgs__srv__GetOrigin_Response__Sequence

func GetOrigin_Response__Sequence_to_Go(goSlice *[]GetOrigin_Response, cSlice CGetOrigin_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetOrigin_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__GetOrigin_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetOrigin_Response * uintptr(i)),
		))
		GetOrigin_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetOrigin_Response__Sequence_to_C(cSlice *CGetOrigin_Response__Sequence, goSlice []GetOrigin_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__GetOrigin_Response)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__GetOrigin_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__GetOrigin_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetOrigin_Response * uintptr(i)),
		))
		GetOrigin_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetOrigin_Response__Array_to_Go(goSlice []GetOrigin_Response, cSlice []CGetOrigin_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetOrigin_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetOrigin_Response__Array_to_C(cSlice []CGetOrigin_Response, goSlice []GetOrigin_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetOrigin_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
