/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/get_px4_param_float.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/GetPx4ParamFloat_Request", GetPx4ParamFloat_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetPx4ParamFloat_Request
// function instead.
type GetPx4ParamFloat_Request struct {
	ParamName string `yaml:"param_name"`
}

// NewGetPx4ParamFloat_Request creates a new GetPx4ParamFloat_Request with default values.
func NewGetPx4ParamFloat_Request() *GetPx4ParamFloat_Request {
	self := GetPx4ParamFloat_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetPx4ParamFloat_Request) Clone() *GetPx4ParamFloat_Request {
	c := &GetPx4ParamFloat_Request{}
	c.ParamName = t.ParamName
	return c
}

func (t *GetPx4ParamFloat_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetPx4ParamFloat_Request) SetDefaults() {
	t.ParamName = ""
}

// CloneGetPx4ParamFloat_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetPx4ParamFloat_RequestSlice(dst, src []GetPx4ParamFloat_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetPx4ParamFloat_RequestTypeSupport types.MessageTypeSupport = _GetPx4ParamFloat_RequestTypeSupport{}

type _GetPx4ParamFloat_RequestTypeSupport struct{}

func (t _GetPx4ParamFloat_RequestTypeSupport) New() types.Message {
	return NewGetPx4ParamFloat_Request()
}

func (t _GetPx4ParamFloat_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__GetPx4ParamFloat_Request
	return (unsafe.Pointer)(C.fog_msgs__srv__GetPx4ParamFloat_Request__create())
}

func (t _GetPx4ParamFloat_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__GetPx4ParamFloat_Request__destroy((*C.fog_msgs__srv__GetPx4ParamFloat_Request)(pointer_to_free))
}

func (t _GetPx4ParamFloat_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetPx4ParamFloat_Request)
	mem := (*C.fog_msgs__srv__GetPx4ParamFloat_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.param_name), m.ParamName)
}

func (t _GetPx4ParamFloat_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetPx4ParamFloat_Request)
	mem := (*C.fog_msgs__srv__GetPx4ParamFloat_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ParamName, unsafe.Pointer(&mem.param_name))
}

func (t _GetPx4ParamFloat_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__GetPx4ParamFloat_Request())
}

type CGetPx4ParamFloat_Request = C.fog_msgs__srv__GetPx4ParamFloat_Request
type CGetPx4ParamFloat_Request__Sequence = C.fog_msgs__srv__GetPx4ParamFloat_Request__Sequence

func GetPx4ParamFloat_Request__Sequence_to_Go(goSlice *[]GetPx4ParamFloat_Request, cSlice CGetPx4ParamFloat_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetPx4ParamFloat_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__GetPx4ParamFloat_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetPx4ParamFloat_Request * uintptr(i)),
		))
		GetPx4ParamFloat_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetPx4ParamFloat_Request__Sequence_to_C(cSlice *CGetPx4ParamFloat_Request__Sequence, goSlice []GetPx4ParamFloat_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__GetPx4ParamFloat_Request)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__GetPx4ParamFloat_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__GetPx4ParamFloat_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__GetPx4ParamFloat_Request * uintptr(i)),
		))
		GetPx4ParamFloat_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetPx4ParamFloat_Request__Array_to_Go(goSlice []GetPx4ParamFloat_Request, cSlice []CGetPx4ParamFloat_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetPx4ParamFloat_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetPx4ParamFloat_Request__Array_to_C(cSlice []CGetPx4ParamFloat_Request, goSlice []GetPx4ParamFloat_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetPx4ParamFloat_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
