/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	nav_msgs_msg "github.com/tiiuae/rclgo-msgs/nav_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c
#cgo LDFLAGS: -lnav_msgs__rosidl_typesupport_c -lnav_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/path_to_local.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/PathToLocal_Response", PathToLocal_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewPathToLocal_Response
// function instead.
type PathToLocal_Response struct {
	Path nav_msgs_msg.Path `yaml:"path"`
	Success bool `yaml:"success"`
	Message string `yaml:"message"`
}

// NewPathToLocal_Response creates a new PathToLocal_Response with default values.
func NewPathToLocal_Response() *PathToLocal_Response {
	self := PathToLocal_Response{}
	self.SetDefaults()
	return &self
}

func (t *PathToLocal_Response) Clone() *PathToLocal_Response {
	c := &PathToLocal_Response{}
	c.Path = *t.Path.Clone()
	c.Success = t.Success
	c.Message = t.Message
	return c
}

func (t *PathToLocal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *PathToLocal_Response) SetDefaults() {
	t.Path.SetDefaults()
	t.Success = false
	t.Message = ""
}

// ClonePathToLocal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePathToLocal_ResponseSlice(dst, src []PathToLocal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PathToLocal_ResponseTypeSupport types.MessageTypeSupport = _PathToLocal_ResponseTypeSupport{}

type _PathToLocal_ResponseTypeSupport struct{}

func (t _PathToLocal_ResponseTypeSupport) New() types.Message {
	return NewPathToLocal_Response()
}

func (t _PathToLocal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__PathToLocal_Response
	return (unsafe.Pointer)(C.fog_msgs__srv__PathToLocal_Response__create())
}

func (t _PathToLocal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__PathToLocal_Response__destroy((*C.fog_msgs__srv__PathToLocal_Response)(pointer_to_free))
}

func (t _PathToLocal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*PathToLocal_Response)
	mem := (*C.fog_msgs__srv__PathToLocal_Response)(dst)
	nav_msgs_msg.PathTypeSupport.AsCStruct(unsafe.Pointer(&mem.path), &m.Path)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.message), m.Message)
}

func (t _PathToLocal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PathToLocal_Response)
	mem := (*C.fog_msgs__srv__PathToLocal_Response)(ros2_message_buffer)
	nav_msgs_msg.PathTypeSupport.AsGoStruct(&m.Path, unsafe.Pointer(&mem.path))
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Message, unsafe.Pointer(&mem.message))
}

func (t _PathToLocal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__PathToLocal_Response())
}

type CPathToLocal_Response = C.fog_msgs__srv__PathToLocal_Response
type CPathToLocal_Response__Sequence = C.fog_msgs__srv__PathToLocal_Response__Sequence

func PathToLocal_Response__Sequence_to_Go(goSlice *[]PathToLocal_Response, cSlice CPathToLocal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PathToLocal_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__PathToLocal_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__PathToLocal_Response * uintptr(i)),
		))
		PathToLocal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func PathToLocal_Response__Sequence_to_C(cSlice *CPathToLocal_Response__Sequence, goSlice []PathToLocal_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__PathToLocal_Response)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__PathToLocal_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__PathToLocal_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__PathToLocal_Response * uintptr(i)),
		))
		PathToLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func PathToLocal_Response__Array_to_Go(goSlice []PathToLocal_Response, cSlice []CPathToLocal_Response) {
	for i := 0; i < len(cSlice); i++ {
		PathToLocal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PathToLocal_Response__Array_to_C(cSlice []CPathToLocal_Response, goSlice []PathToLocal_Response) {
	for i := 0; i < len(goSlice); i++ {
		PathToLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
