/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/set_px4_param_int.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/SetPx4ParamInt_Request", SetPx4ParamInt_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSetPx4ParamInt_Request
// function instead.
type SetPx4ParamInt_Request struct {
	ParamName string `yaml:"param_name"`
	Value int64 `yaml:"value"`
}

// NewSetPx4ParamInt_Request creates a new SetPx4ParamInt_Request with default values.
func NewSetPx4ParamInt_Request() *SetPx4ParamInt_Request {
	self := SetPx4ParamInt_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetPx4ParamInt_Request) Clone() *SetPx4ParamInt_Request {
	c := &SetPx4ParamInt_Request{}
	c.ParamName = t.ParamName
	c.Value = t.Value
	return c
}

func (t *SetPx4ParamInt_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetPx4ParamInt_Request) SetDefaults() {
	t.ParamName = ""
	t.Value = 0
}

// CloneSetPx4ParamInt_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetPx4ParamInt_RequestSlice(dst, src []SetPx4ParamInt_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetPx4ParamInt_RequestTypeSupport types.MessageTypeSupport = _SetPx4ParamInt_RequestTypeSupport{}

type _SetPx4ParamInt_RequestTypeSupport struct{}

func (t _SetPx4ParamInt_RequestTypeSupport) New() types.Message {
	return NewSetPx4ParamInt_Request()
}

func (t _SetPx4ParamInt_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__SetPx4ParamInt_Request
	return (unsafe.Pointer)(C.fog_msgs__srv__SetPx4ParamInt_Request__create())
}

func (t _SetPx4ParamInt_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__SetPx4ParamInt_Request__destroy((*C.fog_msgs__srv__SetPx4ParamInt_Request)(pointer_to_free))
}

func (t _SetPx4ParamInt_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetPx4ParamInt_Request)
	mem := (*C.fog_msgs__srv__SetPx4ParamInt_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.param_name), m.ParamName)
	mem.value = C.int64_t(m.Value)
}

func (t _SetPx4ParamInt_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetPx4ParamInt_Request)
	mem := (*C.fog_msgs__srv__SetPx4ParamInt_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ParamName, unsafe.Pointer(&mem.param_name))
	m.Value = int64(mem.value)
}

func (t _SetPx4ParamInt_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__SetPx4ParamInt_Request())
}

type CSetPx4ParamInt_Request = C.fog_msgs__srv__SetPx4ParamInt_Request
type CSetPx4ParamInt_Request__Sequence = C.fog_msgs__srv__SetPx4ParamInt_Request__Sequence

func SetPx4ParamInt_Request__Sequence_to_Go(goSlice *[]SetPx4ParamInt_Request, cSlice CSetPx4ParamInt_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetPx4ParamInt_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__SetPx4ParamInt_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__SetPx4ParamInt_Request * uintptr(i)),
		))
		SetPx4ParamInt_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SetPx4ParamInt_Request__Sequence_to_C(cSlice *CSetPx4ParamInt_Request__Sequence, goSlice []SetPx4ParamInt_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__SetPx4ParamInt_Request)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__SetPx4ParamInt_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__SetPx4ParamInt_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__SetPx4ParamInt_Request * uintptr(i)),
		))
		SetPx4ParamInt_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SetPx4ParamInt_Request__Array_to_Go(goSlice []SetPx4ParamInt_Request, cSlice []CSetPx4ParamInt_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetPx4ParamInt_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetPx4ParamInt_Request__Array_to_C(cSlice []CSetPx4ParamInt_Request, goSlice []SetPx4ParamInt_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetPx4ParamInt_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
