/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/waypoint_to_local.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("fog_msgs/WaypointToLocal_Response", WaypointToLocal_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewWaypointToLocal_Response
// function instead.
type WaypointToLocal_Response struct {
	LocalX float64 `yaml:"local_x"`
	LocalY float64 `yaml:"local_y"`
	LocalZ float64 `yaml:"local_z"`
	Success bool `yaml:"success"`
	Message string `yaml:"message"`
}

// NewWaypointToLocal_Response creates a new WaypointToLocal_Response with default values.
func NewWaypointToLocal_Response() *WaypointToLocal_Response {
	self := WaypointToLocal_Response{}
	self.SetDefaults()
	return &self
}

func (t *WaypointToLocal_Response) Clone() *WaypointToLocal_Response {
	c := &WaypointToLocal_Response{}
	c.LocalX = t.LocalX
	c.LocalY = t.LocalY
	c.LocalZ = t.LocalZ
	c.Success = t.Success
	c.Message = t.Message
	return c
}

func (t *WaypointToLocal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *WaypointToLocal_Response) SetDefaults() {
	t.LocalX = 0
	t.LocalY = 0
	t.LocalZ = 0
	t.Success = false
	t.Message = ""
}

// CloneWaypointToLocal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneWaypointToLocal_ResponseSlice(dst, src []WaypointToLocal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var WaypointToLocal_ResponseTypeSupport types.MessageTypeSupport = _WaypointToLocal_ResponseTypeSupport{}

type _WaypointToLocal_ResponseTypeSupport struct{}

func (t _WaypointToLocal_ResponseTypeSupport) New() types.Message {
	return NewWaypointToLocal_Response()
}

func (t _WaypointToLocal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__WaypointToLocal_Response
	return (unsafe.Pointer)(C.fog_msgs__srv__WaypointToLocal_Response__create())
}

func (t _WaypointToLocal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__WaypointToLocal_Response__destroy((*C.fog_msgs__srv__WaypointToLocal_Response)(pointer_to_free))
}

func (t _WaypointToLocal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*WaypointToLocal_Response)
	mem := (*C.fog_msgs__srv__WaypointToLocal_Response)(dst)
	mem.local_x = C.double(m.LocalX)
	mem.local_y = C.double(m.LocalY)
	mem.local_z = C.double(m.LocalZ)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.message), m.Message)
}

func (t _WaypointToLocal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*WaypointToLocal_Response)
	mem := (*C.fog_msgs__srv__WaypointToLocal_Response)(ros2_message_buffer)
	m.LocalX = float64(mem.local_x)
	m.LocalY = float64(mem.local_y)
	m.LocalZ = float64(mem.local_z)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Message, unsafe.Pointer(&mem.message))
}

func (t _WaypointToLocal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__WaypointToLocal_Response())
}

type CWaypointToLocal_Response = C.fog_msgs__srv__WaypointToLocal_Response
type CWaypointToLocal_Response__Sequence = C.fog_msgs__srv__WaypointToLocal_Response__Sequence

func WaypointToLocal_Response__Sequence_to_Go(goSlice *[]WaypointToLocal_Response, cSlice CWaypointToLocal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]WaypointToLocal_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__WaypointToLocal_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__WaypointToLocal_Response * uintptr(i)),
		))
		WaypointToLocal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func WaypointToLocal_Response__Sequence_to_C(cSlice *CWaypointToLocal_Response__Sequence, goSlice []WaypointToLocal_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__WaypointToLocal_Response)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__WaypointToLocal_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__WaypointToLocal_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__WaypointToLocal_Response * uintptr(i)),
		))
		WaypointToLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func WaypointToLocal_Response__Array_to_Go(goSlice []WaypointToLocal_Response, cSlice []CWaypointToLocal_Response) {
	for i := 0; i < len(cSlice); i++ {
		WaypointToLocal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func WaypointToLocal_Response__Array_to_C(cSlice []CWaypointToLocal_Response, goSlice []WaypointToLocal_Response) {
	for i := 0; i < len(goSlice); i++ {
		WaypointToLocal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
